/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modul2;

import javax.swing.JOptionPane;

/**
 *
 * @author MyBook Hype AMD
 */
public class fWarung extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fWarung.class.getName());

    /**
     * Creates new form fWarung
     */
    public fWarung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chkSoto = new javax.swing.JCheckBox();
        chkSate = new javax.swing.JCheckBox();
        chkEsTeh = new javax.swing.JCheckBox();
        chkEsJeruk = new javax.swing.JCheckBox();
        txtSoto = new javax.swing.JTextField();
        txtSate = new javax.swing.JTextField();
        txtEsTeh = new javax.swing.JTextField();
        txtEsJeruk = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rdoCash = new javax.swing.JRadioButton();
        rdoQris = new javax.swing.JRadioButton();
        rdoDebit = new javax.swing.JRadioButton();
        btnHitung = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        btnKosong = new javax.swing.JButton();
        lblCaraBayar = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("MENU");

        jLabel2.setText("Quantity");

        chkSoto.setText("Soto : Rp. 15000");
        chkSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSotoActionPerformed(evt);
            }
        });

        chkSate.setText("Sate : Rp. 17000");
        chkSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSateActionPerformed(evt);
            }
        });

        chkEsTeh.setText("Es Teh : Rp. 3000");
        chkEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsTehActionPerformed(evt);
            }
        });

        chkEsJeruk.setText("Es Jeruk : Rp.4000");

        txtSoto.setText("0");
        txtSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSotoActionPerformed(evt);
            }
        });

        txtSate.setText("0");
        txtSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSateActionPerformed(evt);
            }
        });

        txtEsTeh.setText("0");
        txtEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEsTehActionPerformed(evt);
            }
        });

        txtEsJeruk.setText("0");

        jLabel3.setFont(new java.awt.Font("Amiri", 1, 12)); // NOI18N
        jLabel3.setText("CARA BAYAR");

        buttonGroup1.add(rdoCash);
        rdoCash.setText("Cash");
        rdoCash.setActionCommand("Uang Cash");
        rdoCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCashActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoQris);
        rdoQris.setText("QRIS");
        rdoQris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoQrisActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoDebit);
        rdoDebit.setText("Debit");
        rdoDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDebitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoCash)
                    .addComponent(rdoQris)
                    .addComponent(rdoDebit))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoCash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoQris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoDebit)
                .addGap(28, 28, 28))
        );

        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Alef", 1, 14)); // NOI18N
        lblTotal.setText("Rp.0");

        btnKosong.setText("KOSONGKAN");
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });

        lblCaraBayar.setText("Cara bayar :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(chkSoto))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkSate)
                                    .addComponent(chkEsTeh)
                                    .addComponent(chkEsJeruk))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHitung)
                            .addComponent(jLabel2)
                            .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEsTeh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 167, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblCaraBayar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKosong))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotal)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkSoto)
                    .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkSate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(chkEsJeruk))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEsJeruk)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnHitung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotal)
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaraBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKosong))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
     if(chkSoto.isSelected()){// TODO add your handling code here:
         txtSoto.setEditable(true);
         txtSoto.setText("1");
     }else{
         txtSoto.setEditable(false);
         txtSoto.setText("0");
     }
    }//GEN-LAST:event_chkSotoActionPerformed

    private void chkSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSateActionPerformed

    private void chkEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsTehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEsTehActionPerformed

    private void txtSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSotoActionPerformed

    private void txtSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSateActionPerformed

    private void txtEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEsTehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEsTehActionPerformed

    private void rdoCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoCashActionPerformed

    private void rdoQrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoQrisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoQrisActionPerformed

    private void rdoDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDebitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoDebitActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
     boolean lDataOke= true;// TODO add your handling code here:
     //cek ada atau tidak
     //menu di pesan tetapi tidak menuliskan quantity
     //jika ada makan variabel 1DataOke menjadi false
     
     if(chkSoto.isSelected()&& txtSoto.getText()=="")
         lDataOke =false;
     if(chkSate.isSelected()&& txtSate.getText()=="")
         lDataOke =false;
     if(chkEsTeh.isSelected()&& txtEsTeh.getText()=="")
         lDataOke=false;
     if(chkEsJeruk.isSelected()&& txtEsJeruk.getText()=="")
         lDataOke=false;
     //jika variabel lDataOke==false,berarti masih ada kesalahan
     //sehingga perlu dimunculkan pesan kesalahan
     
     if(!lDataOke){
         JOptionPane.showMessageDialog(this,"Data Dilengkapi dahulu");
     }else{
         //untuk memudahkan,buat variabel baru untuk menampung data
         int nSoto = Integer.parseInt(txtSoto.getText());
         int nSate = Integer.parseInt(txtSate.getText());
         int nEsTeh = Integer.parseInt(txtEsTeh.getText());
         int nEsJeruk = Integer.parseInt(txtEsJeruk.getText());
         
         //hitung total
         int nTotal=(15000* nSoto)+
                 (17000* nSate)+(3000* nEsTeh)+(4000* nEsJeruk);
         lblTotal.setText("Rp. "+nTotal);
          //bagian ini untuk menampilkan cara bayar
          if(rdoCash.isSelected())
              lblCaraBayar.setText(rdoCash.getActionCommand());
          if(rdoQris.isSelected())
              lblCaraBayar.setText(rdoQris.getActionCommand());
          if(rdoDebit.isSelected())
              lblCaraBayar.setText(rdoDebit.getActionCommand());
     }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
    chkSoto.setSelected(false); // TODO add your handling code here:
    chkSate.setSelected(false);
    chkEsTeh.setSelected(false);
    chkEsJeruk.setSelected(false);
    txtSoto.setText("0");
    txtSate.setText("0");
    txtEsTeh.setText("0");
    txtEsJeruk.setText("0");
    txtSoto.setEditable(false);
    txtSate.setEditable(false);
    txtEsTeh.setEditable(false);
    txtEsJeruk.setEditable(false);
    rdoCash.setSelected(true);
    lblTotal.setText("Rp.0");
    lblCaraBayar.setText("Cara Bayar");
    
    
    
    }//GEN-LAST:event_btnKosongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fWarung().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKosong;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkEsJeruk;
    private javax.swing.JCheckBox chkEsTeh;
    private javax.swing.JCheckBox chkSate;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCaraBayar;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rdoCash;
    private javax.swing.JRadioButton rdoDebit;
    private javax.swing.JRadioButton rdoQris;
    private javax.swing.JTextField txtEsJeruk;
    private javax.swing.JTextField txtEsTeh;
    private javax.swing.JTextField txtSate;
    private javax.swing.JTextField txtSoto;
    // End of variables declaration//GEN-END:variables
}
